// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRHH.WhatsApp.Infrastructure.Persistencia;

#nullable disable

namespace RRHH.WhatsApp.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(RrhhDbContext))]
    [Migration("20260917153657_AdjuntosEntrantes")]
    partial class AdjuntosEntrantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.AlertaOperativa", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaPrimera")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResuelta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltima")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ocurrencias")
                        .HasColumnType("int");

                    b.Property<int?>("ResueltaPorAnalistaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("AlertaId");

                    b.HasIndex("ResueltaPorAnalistaId");

                    b.HasIndex(new[] { "Tipo", "Clave" }, "IX_AlertasOperativas_AbiertaUnica")
                        .IsUnique()
                        .HasFilter("[FechaResuelta] IS NULL");

                    b.ToTable("AlertasOperativas", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Analista", b =>
                {
                    b.Property<int>("AnalistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalistaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaContrasena")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashContrasena")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("AnalistaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Analistas", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.AnalistaCuenta", b =>
                {
                    b.Property<int>("AnalistaCuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalistaCuentaId"));

                    b.Property<int>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsBackup")
                        .HasColumnType("bit");

                    b.HasKey("AnalistaCuentaId");

                    b.HasIndex("AnalistaId", "CuentaId")
                        .IsUnique();

                    b.HasIndex(new[] { "CuentaId" }, "IX_AnalistaCuenta_RespaldoUnicoPorCuenta")
                        .IsUnique()
                        .HasFilter("[EsBackup] = 1");

                    b.HasIndex(new[] { "CuentaId" }, "IX_AnalistaCuenta_TitularUnicoPorCuenta")
                        .IsUnique()
                        .HasFilter("[EsBackup] = 0");

                    b.ToTable("AnalistaCuenta", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Auditoria", b =>
                {
                    b.Property<long>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("EntidadTipo", "EntidadId", "Fecha");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Ausencia", b =>
                {
                    b.Property<int>("AusenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AusenciaId"));

                    b.Property<int>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAvisoRetorno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AusenciaId");

                    b.HasIndex("AnalistaId", "FechaInicio", "FechaFin");

                    b.ToTable("Ausencias", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.ConfiguracionRegla", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Clave");

                    b.ToTable("ConfiguracionReglas", (string)null);

                    b.HasData(
                        new
                        {
                            Clave = "escalamiento.horas",
                            Descripcion = "Regla 2: horas sin respuesta del titular antes de escalar al respaldo fijo.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "2"
                        },
                        new
                        {
                            Clave = "escalamiento.solo_horario_laboral",
                            Descripcion = "Si es true, esas horas solo corren dentro del horario de atencion, para que un mensaje recibido al cierre no escale de madrugada.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "true"
                        },
                        new
                        {
                            Clave = "jobforms.recordatorio_horas",
                            Descripcion = "Regla 9: horas tras enviar el link antes de recordarle al postulante que complete el formulario.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "24"
                        },
                        new
                        {
                            Clave = "jobforms.aviso_analista_horas",
                            Descripcion = "Regla 9: horas tras enviar el link antes de avisarle al analista que el postulante no completo el formulario.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "48"
                        },
                        new
                        {
                            Clave = "conversacion.repregunta_dias",
                            Descripcion = "Regla 9: dias de inactividad tras los cuales el bot vuelve a preguntar la empresa.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "3"
                        },
                        new
                        {
                            Clave = "conversacion.archivado_dias",
                            Descripcion = "Regla 16: dias sin actividad y sin marca de contratado o reingreso antes del archivado definitivo.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "90"
                        },
                        new
                        {
                            Clave = "datos.retencion_cv_dias",
                            Descripcion = "Regla 17: dias de retencion de CVs antes de la purga, alineado a la Ley de Proteccion de Datos Personales.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "365"
                        },
                        new
                        {
                            Clave = "datos.version_aviso_privacidad",
                            Descripcion = "Regla 17: version del aviso de privacidad vigente, que se sella en cada respuesta de JobForms.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "2026-08-v1"
                        },
                        new
                        {
                            Clave = "envio.maximo_por_segundo",
                            Descripcion = "Seccion 9.6.4: tope de velocidad de envio saliente hacia Meta, por proceso emisor, para no repetir el patron que causo el bloqueo.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "10"
                        },
                        new
                        {
                            Clave = "outbox.reintentos_maximos",
                            Descripcion = "Seccion 9.6.2: intentos de procesamiento de un evento de la outbox antes de marcarlo como fallido.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "5"
                        },
                        new
                        {
                            Clave = "envio.reintentos_maximos",
                            Descripcion = "Intentos de un saliente rechazado por causa transitoria antes de darlo por perdido.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "4"
                        },
                        new
                        {
                            Clave = "envio.reintento_base_segundos",
                            Descripcion = "Base del retroceso exponencial entre reintentos de envio: 1m, 2m, 4m.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "60"
                        },
                        new
                        {
                            Clave = "escalamiento.horas_segundo_nivel",
                            Descripcion = "Regla 2 (A9): horas habiles desde el escalamiento sin respuesta del respaldo antes de avisar a Jefatura.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "2"
                        },
                        new
                        {
                            Clave = "clasificacion.horas_aviso",
                            Descripcion = "Regla 19 (P3): horas habiles en Sin clasificar antes de avisar a Jefatura.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "2"
                        },
                        new
                        {
                            Clave = "menu.reintentos_permitidos",
                            Descripcion = "Regla 19: reintentos del menu sin opcion valida antes de derivar a Sin clasificar.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "1"
                        },
                        new
                        {
                            Clave = "menu.horas_derivacion",
                            Descripcion = "Regla 19 (A12): horas habiles de silencio tras un texto no reconocido antes de derivar a Sin clasificar.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "2"
                        },
                        new
                        {
                            Clave = "transferencia.horas_vencimiento",
                            Descripcion = "Regla 8 (A1): horas habiles hasta que vence una transferencia no urgente sin respuesta.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "2"
                        },
                        new
                        {
                            Clave = "conversacion.aviso_archivado_dias",
                            Descripcion = "Regla 16 (A14): dias antes del archivado en que se avisa al analista.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "7"
                        },
                        new
                        {
                            Clave = "cierre.automatico",
                            Descripcion = "Regla 12 (A11): el cierre de cortesia sale por defecto al descartar; el analista puede marcar no enviar.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "true"
                        },
                        new
                        {
                            Clave = "outbox.retencion_dias_procesados",
                            Descripcion = "Seccion 9.6.2: dias que se conservan los eventos ya procesados de la outbox antes de purgarlos.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "30"
                        },
                        new
                        {
                            Clave = "datos.retencion_adjuntos_dias",
                            Descripcion = "Regla 17: dias de retencion de los adjuntos que llegan por WhatsApp.",
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = "365"
                        });
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Conversacion", b =>
                {
                    b.Property<int>("ConversacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversacionId"));

                    b.Property<int?>("AnalistaAtendiendoId")
                        .HasColumnType("int");

                    b.Property<int?>("CuentaContextoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAvisoFueraHorario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAvisoPendiente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAvisoSegundoNivel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEscalamiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaOptIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPendienteDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTextoNoReconocido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActividad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRespuestaAnalista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoMensajeEntrante")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosMenuFallidos")
                        .HasColumnType("int");

                    b.Property<int?>("OrigenOptIn")
                        .HasColumnType("int");

                    b.Property<int?>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TelefonoE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ConversacionId");

                    b.HasIndex("CuentaContextoId");

                    b.HasIndex("PostulanteId");

                    b.HasIndex("TelefonoE164")
                        .IsUnique();

                    b.HasIndex("AnalistaAtendiendoId", "Estado");

                    b.HasIndex("Estado", "FechaUltimaRespuestaAnalista");

                    b.HasIndex(new[] { "Estado", "FechaUltimaActividad" }, "IX_Conversaciones_EstadoActividad");

                    b.ToTable("Conversaciones", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Cuenta", b =>
                {
                    b.Property<int>("CuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CuentaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cuentas", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.EstadoPostulanteCuenta", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<int>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("EstadoId");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("CuentaId");

                    b.HasIndex("PostulanteId", "CuentaId", "Tipo");

                    b.ToTable("EstadosPostulanteCuenta", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.EtapaKanban", b =>
                {
                    b.Property<int>("EtapaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtapaId"));

                    b.Property<bool>("EsFinal")
                        .HasColumnType("bit");

                    b.Property<int?>("EstadoResultante")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("EtapaId");

                    b.HasIndex("Orden")
                        .IsUnique();

                    b.ToTable("EtapasKanban", (string)null);

                    b.HasData(
                        new
                        {
                            EtapaId = 1,
                            EsFinal = false,
                            Nombre = "Postulante nuevo",
                            Orden = 1
                        },
                        new
                        {
                            EtapaId = 2,
                            EsFinal = false,
                            Nombre = "En revision",
                            Orden = 2
                        },
                        new
                        {
                            EtapaId = 3,
                            EsFinal = false,
                            Nombre = "Entrevista",
                            Orden = 3
                        },
                        new
                        {
                            EtapaId = 4,
                            EsFinal = true,
                            EstadoResultante = 2,
                            Nombre = "Contratado",
                            Orden = 4
                        },
                        new
                        {
                            EtapaId = 5,
                            EsFinal = true,
                            EstadoResultante = 3,
                            Nombre = "Descartado",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.EventoSistema", b =>
                {
                    b.Property<long>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventoId"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosProcesamiento")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("EventoId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex(new[] { "Estado", "Tipo", "FechaCreacion" }, "IX_EventosSistema_Cola");

                    b.ToTable("EventosSistema", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Hc", b =>
                {
                    b.Property<int>("HcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HcId"));

                    b.Property<string>("CodigoAviso")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CodigoJobForms")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlJobForms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("HcId");

                    b.HasIndex("CuentaId", "Estado");

                    b.HasIndex(new[] { "CodigoAviso" }, "IX_HC_CodigoAviso")
                        .IsUnique()
                        .HasFilter("[CodigoAviso] IS NOT NULL");

                    b.ToTable("HC", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.HcCampoOpcional", b =>
                {
                    b.Property<int>("CampoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("HcId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("CampoId");

                    b.HasIndex("HcId");

                    b.ToTable("HCCamposOpcionales", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.HorarioAtencion", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<int?>("CuentaId")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("HorarioId");

                    b.HasIndex("CuentaId", "DiaSemana");

                    b.ToTable("HorarioAtencion", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.JobFormsInvitacion", b =>
                {
                    b.Property<int>("InvitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitacionId"));

                    b.Property<bool>("AvisoAnalistaEnviado")
                        .HasColumnType("bit");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAvisoAnalista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvioLink")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRecordatorio")
                        .HasColumnType("datetime2");

                    b.Property<int>("HcId")
                        .HasColumnType("int");

                    b.Property<int?>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("bit");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvitacionId");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("HcId");

                    b.HasIndex("PostulanteId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Completado", "AvisoAnalistaEnviado", "FechaEnvioLink");

                    b.HasIndex("Completado", "RecordatorioEnviado", "FechaEnvioLink");

                    b.ToTable("JobFormsInvitaciones", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.JobFormsRespuesta", b =>
                {
                    b.Property<int>("RespuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RespuestaId"));

                    b.Property<bool>("ConsentimientoAceptado")
                        .HasColumnType("bit");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DatosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaConsentimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("HcId")
                        .HasColumnType("int");

                    b.Property<int?>("InvitacionId")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<string>("VersionAvisoPrivacidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RespuestaId");

                    b.HasIndex("HcId");

                    b.HasIndex("PostulanteId", "HcId");

                    b.HasIndex(new[] { "InvitacionId" }, "IX_JobFormsRespuestas_Invitacion")
                        .IsUnique()
                        .HasFilter("[InvitacionId] IS NOT NULL");

                    b.ToTable("JobFormsRespuestas", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.LatidoServicio", b =>
                {
                    b.Property<string>("Servicio")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToleranciaSegundos")
                        .HasColumnType("int");

                    b.HasKey("Servicio");

                    b.ToTable("LatidosServicio", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Mensaje", b =>
                {
                    b.Property<long>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MensajeId"));

                    b.Property<int?>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseFallo")
                        .HasColumnType("int");

                    b.Property<string>("ClaveIdempotencia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direccion")
                        .HasColumnType("int");

                    b.Property<string>("ErrorProveedor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoEntrega")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTomaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosEnvio")
                        .HasColumnType("int");

                    b.Property<string>("OpcionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametrosPlantillaJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PlantillaId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ProximoIntentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoSaliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MensajeId");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("PlantillaId");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasFilter("[ProviderMessageId] IS NOT NULL");

                    b.HasIndex("ConversacionId", "FechaEnvio");

                    b.HasIndex("EstadoEntrega", "ClaseFallo", "ProximoIntentoUtc")
                        .HasDatabaseName("IX_Mensajes_PendientesDeReintento")
                        .HasFilter("[ProximoIntentoUtc] IS NOT NULL");

                    b.HasIndex(new[] { "ClaveIdempotencia" }, "IX_Mensajes_ClaveIdempotencia")
                        .IsUnique()
                        .HasFilter("[ClaveIdempotencia] IS NOT NULL");

                    b.HasIndex(new[] { "EstadoEntrega", "FechaEnvio" }, "IX_Mensajes_EnCola")
                        .HasFilter("[EstadoEntrega] = 6");

                    b.ToTable("Mensajes", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.MensajeAdjunto", b =>
                {
                    b.Property<long>("AdjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdjuntoId"));

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosDescarga")
                        .HasColumnType("int");

                    b.Property<long>("MensajeId")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProveedorMedioId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ProximoIntentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ruta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMedio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AdjuntoId");

                    b.HasIndex("MensajeId");

                    b.HasIndex(new[] { "Estado", "FechaRecepcion" }, "IX_MensajesAdjuntos_Estado_FechaRecepcion");

                    b.ToTable("MensajesAdjuntos", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Plantilla", b =>
                {
                    b.Property<int>("PlantillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantillaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadParametros")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NombreMeta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TextoAprobado")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("PlantillaId");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Plantillas", (string)null);

                    b.HasData(
                        new
                        {
                            PlantillaId = 1,
                            Activa = false,
                            CantidadParametros = 1,
                            Categoria = 1,
                            Clave = "fuera_horario",
                            Idioma = "es",
                            NombreMeta = "rrhh_fuera_horario",
                            TextoAprobado = "Hola. Nuestro horario de atencion es {{1}}. Tu mensaje ya quedo registrado y un analista te respondera apenas retomemos la jornada."
                        },
                        new
                        {
                            PlantillaId = 2,
                            Activa = false,
                            CantidadParametros = 3,
                            Categoria = 1,
                            Clave = "recordatorio_24h",
                            Idioma = "es",
                            NombreMeta = "rrhh_recordatorio_formulario",
                            TextoAprobado = "Hola {{1}}. Notamos que aun no completas tu ficha de postulacion para la vacante {{2}}. Puedes hacerlo aqui: {{3}}"
                        },
                        new
                        {
                            PlantillaId = 3,
                            Activa = false,
                            CantidadParametros = 2,
                            Categoria = 1,
                            Clave = "confirmacion_jobforms",
                            Idioma = "es",
                            NombreMeta = "rrhh_confirmacion_formulario",
                            TextoAprobado = "Gracias {{1}}. Recibimos tu ficha para la vacante {{2}}. Un analista revisara tu postulacion y te escribira por este mismo chat."
                        },
                        new
                        {
                            PlantillaId = 4,
                            Activa = false,
                            CantidadParametros = 2,
                            Categoria = 1,
                            Clave = "cierre_cortesia",
                            Idioma = "es",
                            NombreMeta = "rrhh_cierre_cortesia",
                            TextoAprobado = "Hola {{1}}. Agradecemos tu interes en la vacante {{2}}. En esta oportunidad continuaremos con otros perfiles, pero mantendremos tus datos para futuras convocatorias."
                        },
                        new
                        {
                            PlantillaId = 5,
                            Activa = false,
                            CantidadParametros = 1,
                            Categoria = 1,
                            Clave = "vacante_cerrada",
                            Idioma = "es",
                            NombreMeta = "rrhh_vacante_cerrada",
                            TextoAprobado = "La vacante {{1}} ya fue cubierta. Puedes revisar nuestras otras convocatorias activas respondiendo a este mensaje."
                        },
                        new
                        {
                            PlantillaId = 6,
                            Activa = false,
                            CantidadParametros = 1,
                            Categoria = 1,
                            Clave = "reapertura_conversacion",
                            Idioma = "es",
                            NombreMeta = "rrhh_reapertura",
                            TextoAprobado = "Hola {{1}}. Vemos que vuelves a escribirnos. Para ayudarte mejor, indicanos a que empresa corresponde tu consulta."
                        });
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Postulacion", b =>
                {
                    b.Property<int>("PostulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostulacionId"));

                    b.Property<int?>("AnalistaAsignadoId")
                        .HasColumnType("int");

                    b.Property<bool>("CierreCortesiaPendiente")
                        .HasColumnType("bit");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EtapaKanbanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAvisoArchivado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCambioEtapa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierreCortesia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActividad")
                        .HasColumnType("datetime2");

                    b.Property<int>("HcId")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PostulacionId");

                    b.HasIndex("CuentaId");

                    b.HasIndex("EtapaKanbanId");

                    b.HasIndex("Estado", "FechaUltimaActividad");

                    b.HasIndex("HcId", "EtapaKanbanId");

                    b.HasIndex("PostulanteId", "HcId")
                        .IsUnique();

                    b.HasIndex("AnalistaAsignadoId", "CuentaId", "Estado");

                    b.ToTable("Postulaciones", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Postulante", b =>
                {
                    b.Property<int>("PostulanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostulanteId"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TelefonoUltimo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PostulanteId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Postulantes", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Transferencia", b =>
                {
                    b.Property<int>("TransferenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferenciaId"));

                    b.Property<int>("AnalistaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("AnalistaOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostulacionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("Urgente")
                        .HasColumnType("bit");

                    b.HasKey("TransferenciaId");

                    b.HasIndex("AnalistaOrigenId");

                    b.HasIndex("PostulacionId");

                    b.HasIndex("AnalistaDestinoId", "Estado");

                    b.HasIndex(new[] { "ConversacionId" }, "IX_Transferencias_ConversacionId");

                    b.HasIndex(new[] { "ConversacionId" }, "IX_Transferencias_PendienteUnica")
                        .IsUnique()
                        .HasFilter("[Estado] = 1");

                    b.ToTable("Transferencias", (string)null);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.AlertaOperativa", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", null)
                        .WithMany()
                        .HasForeignKey("ResueltaPorAnalistaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.AnalistaCuenta", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "Analista")
                        .WithMany("Cuentas")
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Cuenta", "Cuenta")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Ausencia", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "Analista")
                        .WithMany("Ausencias")
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analista");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Conversacion", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "AnalistaAtendiendo")
                        .WithMany()
                        .HasForeignKey("AnalistaAtendiendoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Cuenta", "CuentaContexto")
                        .WithMany()
                        .HasForeignKey("CuentaContextoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnalistaAtendiendo");

                    b.Navigation("CuentaContexto");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.EstadoPostulanteCuenta", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "Analista")
                        .WithMany()
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Postulante", "Postulante")
                        .WithMany("Estados")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Cuenta");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Hc", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Cuenta", "Cuenta")
                        .WithMany("Vacantes")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.HcCampoOpcional", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Hc", "Hc")
                        .WithMany("CamposOpcionales")
                        .HasForeignKey("HcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hc");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.HorarioAtencion", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.JobFormsInvitacion", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Hc", "Hc")
                        .WithMany()
                        .HasForeignKey("HcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversacion");

                    b.Navigation("Hc");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.JobFormsRespuesta", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Hc", "Hc")
                        .WithMany()
                        .HasForeignKey("HcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.JobFormsInvitacion", "Invitacion")
                        .WithMany()
                        .HasForeignKey("InvitacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hc");

                    b.Navigation("Invitacion");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Mensaje", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "Analista")
                        .WithMany()
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Plantilla", "Plantilla")
                        .WithMany()
                        .HasForeignKey("PlantillaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Analista");

                    b.Navigation("Conversacion");

                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.MensajeAdjunto", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Mensaje", "Mensaje")
                        .WithMany("Adjuntos")
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Postulacion", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "AnalistaAsignado")
                        .WithMany()
                        .HasForeignKey("AnalistaAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.EtapaKanban", "EtapaKanban")
                        .WithMany()
                        .HasForeignKey("EtapaKanbanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Hc", "Hc")
                        .WithMany()
                        .HasForeignKey("HcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Postulante", "Postulante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalistaAsignado");

                    b.Navigation("Cuenta");

                    b.Navigation("EtapaKanban");

                    b.Navigation("Hc");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Transferencia", b =>
                {
                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "AnalistaDestino")
                        .WithMany()
                        .HasForeignKey("AnalistaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Analista", "AnalistaOrigen")
                        .WithMany()
                        .HasForeignKey("AnalistaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.WhatsApp.Domain.Entidades.Postulacion", "Postulacion")
                        .WithMany()
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnalistaDestino");

                    b.Navigation("AnalistaOrigen");

                    b.Navigation("Conversacion");

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Analista", b =>
                {
                    b.Navigation("Ausencias");

                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Cuenta", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Vacantes");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Hc", b =>
                {
                    b.Navigation("CamposOpcionales");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Mensaje", b =>
                {
                    b.Navigation("Adjuntos");
                });

            modelBuilder.Entity("RRHH.WhatsApp.Domain.Entidades.Postulante", b =>
                {
                    b.Navigation("Estados");

                    b.Navigation("Postulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
